build_tree_sitter:
    image: archlinux:latest
    script:
        - pacman -Syu --noconfirm
        - pacman -S --noconfirm tree-sitter-cli nodejs emscripten
        - source /etc/profile.d/emscripten.sh
        - tree-sitter generate
        - tree-sitter build --wasm
    artifacts:
        paths:
            - tree-sitter-charon.wasm

build_tree_sitter_abi_14:
    image: archlinux:latest
    script:
        - pacman -Syu --noconfirm
        - pacman -S --noconfirm tree-sitter-cli nodejs emscripten
        - source /etc/profile.d/emscripten.sh
        - tree-sitter generate --abi 14
        - tree-sitter build --wasm
    artifacts:
        paths:
            - tree-sitter-charon.wasm
